# Generated by Django 5.2.5 on 2025-08-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='report_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(default='done', max_length=24),
        ),
    ]
