# Generated by Django 5.2.5 on 2025-08-27 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_importbatch_report_path_alter_importbatch_status'),
        ('packages', '0002_alter_package_options_package_addr_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportErrorRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('error', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TruckReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('total_packages', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TruckReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(default='staged', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='importbatch',
            options={'ordering': ('-imported_at',)},
        ),
        migrations.RemoveField(
            model_name='importbatch',
            name='imported_by',
        ),
        migrations.AddField(
            model_name='importbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='file_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='source',
            field=models.CharField(choices=[('speedx_csv', 'SpeedX CSV'), ('speedx_api', 'SpeedX API'), ('manual', 'Manual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(default='processing', max_length=20),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['imported_at'], name='imports_imp_importe_49715f_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['status'], name='imports_imp_status_22f3a0_idx'),
        ),
        migrations.AddField(
            model_name='importerrorrow',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='imports.importbatch'),
        ),
        migrations.AddField(
            model_name='truckreceipt',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='truck_receipts', to='packages.warehouse'),
        ),
        migrations.AddField(
            model_name='truckreceiptitem',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='imports.truckreceipt'),
        ),
    ]
