# Generated by Django 5.2.5 on 2025-08-27 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=16, unique=True)),
                ('type', models.CharField(default='car', max_length=24)),
                ('capacity', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=24)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='device_os',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='driver',
            name='device_token',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(default='active', max_length=24),
        ),
        migrations.CreateModel(
            name='LocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('battery', models.IntegerField(blank=True, null=True)),
                ('captured_at', models.DateTimeField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pings', to='drivers.driver')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.vehicle'),
        ),
    ]
