# Generated by Django 5.2.5 on 2025-08-29 15:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_vehicle_driver_device_os_driver_device_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationping',
            options={'ordering': ['-captured_at']},
        ),
        migrations.AddField(
            model_name='driver',
            name='last_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='drivers.vehicle'),
        ),
        migrations.AlterField(
            model_name='locationping',
            name='battery',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='locationping',
            name='captured_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='locationping',
            name='speed',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['status'], name='drivers_dri_status_d7a5f5_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['last_location_at'], name='drivers_dri_last_lo_20e4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='locationping',
            index=models.Index(fields=['driver', 'captured_at'], name='drivers_loc_driver__0ec9d5_idx'),
        ),
    ]
