# Generated by Django 5.2.5 on 2025-08-27 18:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_vehicle_driver_device_os_driver_device_token_and_more'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='package',
            name='addr_city',
            field=models.CharField(db_index=True, default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='addr_state',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='package',
            name='addr_zip',
            field=models.CharField(db_index=True, default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_packages', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='package',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='package',
            name='cod_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='package',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='dest_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='dest_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='last_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='note',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='package',
            name='out_for_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='promised_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='speedx_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='addr_street',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('in_warehouse', 'In warehouse'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('failed_attempt', 'Failed attempt'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], db_index=True, default='received', max_length=32),
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('result', models.CharField(choices=[('delivered', 'Delivered'), ('failed', 'Failed')], max_length=16)),
                ('reason_code', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('at_ts', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driver')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='packages.package')),
            ],
            options={
                'ordering': ('package', 'attempt_no'),
            },
        ),
        migrations.CreateModel(
            name='PackageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assigned', 'Assigned'), ('ofd', 'Out for delivery'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('returned', 'Returned')], max_length=40)),
                ('status_from', models.CharField(blank=True, max_length=32)),
                ('status_to', models.CharField(max_length=32)),
                ('at_ts', models.DateTimeField(auto_now_add=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driver')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='packages.package')),
            ],
            options={
                'ordering': ('-at_ts', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PodPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_local', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='packages.deliveryattempt')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pod_photos', to='packages.package')),
            ],
            options={
                'ordering': ('-taken_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('address', models.CharField(blank=True, max_length=180)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ('-created_at', 'name'),
                'indexes': [models.Index(fields=['name'], name='packages_wa_name_a70cfa_idx'), models.Index(fields=['created_at'], name='packages_wa_created_ea0dc2_idx')],
            },
        ),
        migrations.AddField(
            model_name='package',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='packages.warehouse'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['status'], name='packages_pa_status_1e0453_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['assigned_driver', 'status'], name='packages_pa_assigne_184bde_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['promised_date'], name='packages_pa_promise_e451c0_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['addr_zip'], name='packages_pa_addr_zi_fe8d23_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['addr_city'], name='packages_pa_addr_ci_2c1934_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['created_at'], name='packages_pa_created_20d1e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_count__gte', 0)), name='packages_attempt_count_gte_0'),
        ),
        migrations.AddIndex(
            model_name='deliveryattempt',
            index=models.Index(fields=['package', 'attempt_no'], name='packages_de_package_ddb248_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryattempt',
            index=models.Index(fields=['result'], name='packages_de_result_b36c2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryattempt',
            constraint=models.UniqueConstraint(fields=('package', 'attempt_no'), name='unique_package_attempt_no'),
        ),
        migrations.AddIndex(
            model_name='packageevent',
            index=models.Index(fields=['package', '-at_ts'], name='packages_pa_package_e5ffbb_idx'),
        ),
        migrations.AddIndex(
            model_name='packageevent',
            index=models.Index(fields=['type'], name='packages_pa_type_6d6ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='podphoto',
            index=models.Index(fields=['package'], name='packages_po_package_b6fffa_idx'),
        ),
        migrations.AddIndex(
            model_name='podphoto',
            index=models.Index(fields=['attempt'], name='packages_po_attempt_db15a0_idx'),
        ),
        migrations.AddIndex(
            model_name='podphoto',
            index=models.Index(fields=['taken_at'], name='packages_po_taken_a_e5b738_idx'),
        ),
    ]
