# Generated by Django 5.2.5 on 2025-08-27 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('drivers', '0002_vehicle_driver_device_os_driver_device_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filter_json', models.JSONField(default=dict)),
                ('total', models.IntegerField(default=0)),
                ('assigned', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('zip', 'ZIP'), ('city', 'City')], db_index=True, max_length=10)),
                ('pattern', models.CharField(db_index=True, max_length=40)),
                ('priority', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_rules', to='drivers.driver')),
            ],
            options={
                'ordering': ('-priority', 'rule_type', 'pattern'),
            },
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.AddIndex(
            model_name='assignmentrule',
            index=models.Index(fields=['rule_type', 'pattern', 'enabled'], name='assignments_rule_ty_f3fbb1_idx'),
        ),
    ]
