# Generated by Django 5.2.5 on 2025-08-28 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignmentbatch_assignmentrule_delete_assignment_and_more'),
        ('drivers', '0002_vehicle_driver_device_os_driver_device_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentbatch',
            options={'ordering': ('-service_date', '-created_at')},
        ),
        migrations.AddField(
            model_name='assignmentbatch',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_batches', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='assignmentbatch',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentbatch',
            name='service_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentbatch',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentbatch',
            name='total_packages',
            field=models.IntegerField(default=0),
        ),
    ]
